# Generated by Django 5.1.2 on 2024-10-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('city', 'time')},
        ),
    ]
